name: first workflow
on: workflow_dispatch

jobs:
  first_job:
    runs-on: ubuntu_latest
    steps:
      - name: first_step
        run: echo "Hello! World"

      - name: second_step
        run: echo "Done!! Bye.." 
